language: node_js
node_js:
  - 4
  - 5
  - 6
before_script:
  - npm install -g jshint codecov
script:
  - jshint .
  - query="http://overpass-api.de/api/interpreter?data=$(<test/kalimantan.osm-q.txt)"
  - wget -O test/kalimantan.osm.json "$query"
  - npm test
  - npm run report-coverage
  - codecov -t ${CODECOV_TOKEN}
